[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node server/railway-production.js'

[variables]
NODE_ENV = 'production'
PORT = '${PORT:-3000}'