[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["echo 'Skipping install phase - will be handled by deployment script'"]

[phases.build]
cmds = ["echo 'Skipping build phase - will be handled by deployment script'"]

[start]
cmd = "node railway-deploy.js"

[variables]
NODE_ENV = "production"
PORT = "${PORT:-3000}"
VITE_API_URL = "https://rickmortyromance-production.up.railway.app"