services:
  - type: web
    name: rick-morty-dating-sim
    env: node
    buildCommand: npm run build
    startCommand: node server/deploy.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    numInstances: 1
    plan: free
    region: oregon
    buildFilter:
      paths:
      - client/**
      - server/**
      - shared/**
      - package.json
      - package-lock.json
      - vite.config.ts
      - tsconfig.json