services:
  - type: web
    name: rickortygame2
    env: node
    plan: free
    buildCommand: npm ci --production=false && npm run build
    startCommand: node migrate.js && NODE_ENV=production node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    branch: main
    rootDir: .